# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-jokl-app-prod"
  description: "team-a-jokl-app-prod"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-jokl-app-prod.demo.kubrix.cloud
      title: Prod Instance of team-a-jokl-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-a-jokl-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-app-prod'
    argocd/app-namespace: adn-team-a
    argocd/app-name: jokl-app-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-a-jokl-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-a-jokl-app-prod&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "team-a"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-jokl-app
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-jokl-app-qa"
  description: "team-a-jokl-app-qa"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-jokl-app-qa.demo.kubrix.cloud
      title: QA Instance of team-a-jokl-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-a-jokl-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-app-qa'
    argocd/app-namespace: adn-team-a
    argocd/app-name: jokl-app-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-a-jokl-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-a-jokl-app-qa&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "team-a"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-jokl-app
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-jokl-app-test"
  description: "team-a-jokl-app-test"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-jokl-app-test.demo.kubrix.cloud
      title: Test Instance of team-a-jokl-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-a-jokl-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jokl-app-test'
    argocd/app-namespace: adn-team-a
    argocd/app-name: jokl-app-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-a-jokl-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-a-jokl-app-test&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "team-a"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-jokl-app
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-jokl-app"
  description: "team-a-jokl-app"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: https://argocd.demo.kubrix.cloud/applications/adn-team-a/team-a-jokl-app?resource=
      title: ArgoCD Application Information of team-a-jokl-app
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-a-jokl-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=team-a-jokl-app'
    argocd/app-namespace: adn-team-a
    argocd/app-name: team-a-jokl-app
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-a-jokl-app-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
